name: Deploy Portfolio

on: 
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Portfolio Repository
      uses: actions/checkout@v3
      with:
        repository: ramanbhandari/portfolio
        personal_token: ${{ secrets.PAT_TOKEN }}
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        external_repository: ramanbhandari/ramanbhandari.github.io
        publish_dir: ./build
        publish_branch: main
        user_name: 'GitHub Actions'
        user_email: 'actions@github.com'
        deploy_key: ${{ secrets.DEPLOY_KEY}}
